# Site settings
title: Bagus Site
email: ilman.bagus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another generic site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bagusilman.com" # the base hostname & protocol for your site
twitter_username: ilmanbag
github_username:  bagusilman
permalink: pretty
# Build settings
markdown: kramdown
#highlighter: false